name: cherrilog
description: Perhaps the simplest and most useful log library for dart. Lightweight and easy to apply.
version: 0.1.1+1
repository: https://github.com/Cranyozen/cherrilog

environment:
  sdk: ^3.1.0

dependencies:
  intl: ^0.19.0
  stack_trace: ^1.11.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - logging
  - logger
  - log
  - utility
